[package]
name = "ldk-node-liquidity-mutinynet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ldk-node = "0.5.0"
env_logger = "0.11"   # or the latest compatible version
log        = "0.4"
